export const PLAYBACK_RATE = 0.7;

export const FADE_IN_VIDEO_MS = 6000;
export const FADE_OUT_VIDEO_SECONDS = 6;
export const FADE_OUT_VIDEO_MS = FADE_OUT_VIDEO_SECONDS * 1000;

export const FADE_IN_MAIN_ABBREVIATED_MS = 2500;

export const FADE_IN_CASTLE_MS = 4000;
export const FADE_IN_CASTLE_BUFFER_SECONDS = 2;
